{{- if .Values.cronjob.enabled }}
{{- range $job, $val := .Values.cronjob.crons }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
{{ include "application.labels" $ | indent 4 }}
spec:
  schedule: {{ .schedule | quote }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "application.name" $ }}
            app.kubernetes.io/instance: {{ $.Release.Name }}
        spec:
        {{- if $.Values.serviceAccount.create }}
          serviceAccountName: {{ include "application.name" $ }}
        {{- end }}
          containers:
            - name: {{ $.Chart.Name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
              - /bin/sh
              args: ["-c", "{{ .args }}"]
              {{- if $.Values.configvalues }}
              envFrom:
                - configMapRef:
                    name: {{ include "application.fullname" $ }}
              {{- end }}
          restartPolicy: OnFailure
---
{{- end }}
{{- end }}    
