{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}
  annotations:
{{- toYaml .Values.secrets.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ include "application.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
{{- toYaml .Values.secrets.values | nindent 2 }}
{{- end }}
