{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "application.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "application.name" . }}
  annotations: {{ toYaml .Values.serviceAccount.serviceAccountAnnotations | nindent 4 }}
{{- end }}
